### ISSUE TITLE
How to make the sections dynamically?

### ISSUE THREAD

**Issue by kevinonik** [klevison/KMAccordionTableViewController#11]
hello,

I am using this in my project and i was stuck at a point where i want to load cells dynamically.

Can you help me out?

**Comment by kevinonik** [comment]
@klevison

**Comment by kevinonik** [comment]
i did this with the following code:

 NSMutableArray *myarr = [[NSMutableArray alloc]init];
    for (int i = 0; i<momemtsARRAY.count; i++) {
        KMSection *section = [self sectionFour];
    
        
        [myarr addObject:section];
    
    }
    
    
    NSArray *returnArr = [myarr copy];
    
//    KMSection *section1 = [self sectionFour];
//    KMSection *section2 = [self sectionFour];
//    KMSection *section3 = [self sectionFour];
//    KMSection *section4 = [self sectionFour];

    return returnArr;


is it going to be ok for big data ?

**Comment by klevison** [comment]
Is it ok?
