### ISSUE TITLE
How to show different data in tableview controller of section 4

### ISSUE THREAD

**Issue by kevinonik** [klevison/KMAccordionTableViewController#12]
I learned how to dynamically create sections. 

Now i am stuck at how to display different data in each section tableviewcontroller

For example I have 4 sections and each section contains a tableviewcontroller. Now i want to display different data in each of it.

**Comment by mucahittekin** [comment]
You need to create a view for each section and attach view to section: 
```objective-c
UIView *viewOfSection = [[UIView alloc] initWithFrame:CGRectMake(0, 0, self.view.frame.size.width, 100)];
//you can add any UI object in this view [viewOfSection addSubview:bla bla]
KMSection *section = [KMSection new];
section.view = viewOfSection;
```

**Comment by ansonngch** [comment]
@kelvinonik mind sharing how you dynamically create the sections?? 

Thank you
