### ISSUE TITLE
Support with multiple Childs of Childs?

### ISSUE THREAD

**Issue by erolando** [klevison/KMAccordionTableViewController#14]
Support with multiple Childs of Childs o levels?

-> Parent 
 -> Group Childrens
  -> Childs

**Comment by klevison** [comment]
It supports whatever (UIView) you want as child.

**Comment by erolando** [comment]
like as this:

![pygdy](https://cloud.githubusercontent.com/assets/1770136/17563331/8f891cf8-5ef4-11e6-818f-e2fbcf390b31.png)

**Comment by klevison** [comment]
Yeah, you can accomplish it with KMAccordionTableViewController, but you need to do something like this:

UITableViewController
   -> KMAccordionTableViewController
      -> UITableViewController
         -> KMAccordionTableViewController
            -> UITableViewController
                -> etc..

You will, need to handle it programmatically and maybe it will be boring. :)

**Comment by JuanFcoMiranda** [comment]
Any example of how to accomplish this??
