### ISSUE TITLE
Use KMAccordionTableViewController in UIViewController

### ISSUE THREAD

**Issue by ghost** [klevison/KMAccordionTableViewController#15]
I would like to use this feature, but not using a UITableViewController, instead of this i want to use a UIViewController that inside has a UITableView.

How can i do that

**Comment by klevison** [comment]
@fdorado985 sorry my late answer, but you have 2 options:

1) Use containers: http://stackoverflow.com/a/34883695/846780
2) programatically use `addchildviewcontroller` http://stackoverflow.com/a/10467794/846780
